### ISSUE TITLE
Add react components for WebRTC

### ISSUE THREAD

**Issue by JoeyDarbyshire** [TranscendVR/transcend#36]
Mute self, mute others, mute individuals, display current users in voice, volume slider?

**Comment by bushidocodes** [comment]
I've been sort of envisioning this as an overlay on top of the A-Frame canvas, sort of like the VR mode button, but none of that would be accessible when in VR mode. Would there be value in implementing any of these controls as a-frame components so that we can mute myself or others while in headset mode?

**Comment by bethqiang** [comment]
I think we should definitely have these accessible while in VR mode, if we're going to have them.

We don't necessarily even have to have all of them--just a mute button would be pretty clutch. Also, I'm not a huge fan of the mute others/mute individuals because I can see the potential for abuse being high, but that's something we can discuss?
